# The URL the site will be built for
base_url = "http://blu3gui7ar.github.io"

theme = "papaya"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true


[languages]

[languages.en]
title = "blu3gui7ar's space"
description = "Lost in the FUN!"
generate_feeds = false
# feed_filenames = "atom.xml"
# The taxonomies to be rendered for the site and their configuration of the default languages
taxonomies = [
    { name = "tags", feed = true, lang = "en" },
    { name = "categories", feed = true, lang = "en" },
]

[languages.en.translations]
funs = "Funs"
blog = "Blog"
about = "About"
recent_funs = "Recent Funs"
more_funs = "More Funs"
recent_blog_posts = "Recent Blog Posts"
more_blog_posts = "More blog posts"
tag = "Tag"
tags = "Tags"
to_all_tags = "To all tags"
category = "Category"
categories = "Categories"
to_all_categories = "To all categories"
view_by = "View by"
other = "Other"
minute = "min"
prev_page = "To newer posts"
next_page = "To older posts"
# Customize your post date format. See: https://tera.netlify.app/docs/#date
date_format = "%B %e, %Y"

[languages.zh]
title = "blu3gui7ar的游乐场"
description = "玩点啥子"
# base_url = "https://blu3gui7ar.github.io/zh"
generate_feeds = false
# The taxonomies to be rendered for the site and their configuration of the default languages
taxonomies = [
    { name = "tags", feed = true, lang = "zh" },
    { name = "categories", feed = true, lang = "zh" },
]

[languages.zh.translations]
funs = "玩"
blog = "博"
about = "关于"
recent_funs = "最近玩"
more_funs = "更多玩"
recent_blog_posts = "近期博文"
more_blog_posts = "更多博文"
tag = "标签"
tags = "所有标签"
to_all_tags = "所有标签"
category = "类别"
categories = "所有类别"
to_all_categories = "所有类别"
view_by = "查看方式"
other = "其他"
minute = "分钟"
prev_page = "上一页"
next_page = "下一页"
# Customize your post date format. See: https://tera.netlify.app/docs/#date
date_format = "%Y 年 %m 月 %d 日"

[extra]
# Put all your custom variables here

color_mode = "auto"

menu_items = [
    { name = "funs", url = "$LANG_BASE_URL/funs", show_recent = true, recent_items = 3, recent_trans_key = "recent_funs", more_trans_key = "more_funs" },
    { name = "blog", url = "$LANG_BASE_URL/blog", show_recent = true, recent_items = 3, recent_trans_key = "recent_blog_posts", more_trans_key = "more_blog_posts" },
    # tag is not a zola section, it's just a link.
    { name = "tags", url = "$LANG_BASE_URL/tags" },
    { name = "about", url = "$LANG_BASE_URL/about", show_recent = false },
]

# Open Graph Protocol objects. See: https://ogp.me/
[extra.ogp]
locale = "en_US"
first_name = "blu3gui7ar"
last_name = ""
gender = "male"
username = "blu3gui7ar"

# CDN links
[extra.cdn]
font_awesome = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
